# Configuration Netlify pour IATA CBTA Platform
[build]
  # Commande de build
  command = "bun run build"
  # Dossier à publier
  publish = "dist"
  # Commande d'installation des dépendances
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  # Version Node.js
  NODE_VERSION = "18"
  # Activer bun
  BUN_VERSION = "1.0.0"

# Optimisations des assets
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pas de cache pour le service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Configuration des redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirection HTTPS
[[redirects]]
  from = "http://iata-cbta-platform.netlify.app/*"
  to = "https://iata-cbta-platform.netlify.app/:splat"
  status = 301
  force = true

# Support des formulaires Netlify
[build.processing.skip]
  # Ne pas traiter les fichiers de formulaires
  forms = false